name: Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, macOS]
        arch: [amd64, arm64]
        exclude:
          - os: macOS
            arch: amd64  # Exclude macOS amd64 if not needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod' # Use your Go version file

      - name: Set up QEMU
        if: runner.os == 'Linux' && matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'linux/arm64'

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bcrypt-${{ matrix.os }}-${{ matrix.arch }}
          # Replace 'myapp' with your actual application name

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bcrypt
          path: bcrypt-${{ matrix.os }}-${{ matrix.arch }}
